import React from 'react';  

var moviedata=[
  {
    id: 1,
    nameChinese:'阿拉丁1',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home: require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/1.jpg'),name:'彼得·法雷里', name2:'导演'},
            {arl:require('./image/week1/2.jpg'),name:'维果·莫腾森', name2:'饰 托尼·利'},
            {arl:require('./image/week1/3.jpg'),name:'马赫沙拉·阿里', name2:'饰 唐·雪利'},
            {arl:require('./image/week1/4.jpg'),name:'琳达·卡德里尼', name2:'饰 德洛瑞丝'},
            {arl:require('./image/week1/5.jpg'),name:'塞巴斯蒂安·马尼斯科', name2:'饰 约翰尼'},
            {arl:require('./image/week1/6.jpg'),name:'迪米特·D·马里诺夫', name2:'饰 奥列格'},
            {arl:require('./image/week1/7.jpg'),name:'迈克·哈顿', name2:'饰 乔治'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 2,
    nameChinese:'阿拉丁2',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 3,
    nameChinese:'阿拉丁3',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 4,
    nameChinese:'阿拉丁4',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 5,
    nameChinese:'阿拉丁5',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 6,
    nameChinese:'阿拉丁6',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
  {
    id: 7,
    nameChinese:'阿拉丁7',
    nameEnglish:'Aladdin',
    prop:'爱情 奇幻 冒险',
    country:'美国/128分钟',
    score: 5,
    language:'super man',
    home:require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
            {arl:require('./image/week1/home.jpg'),name:'维果·莫腾森', name2:'Viggo Mortensen'},
          ],
     vedio:[require('./image/week1/home.jpg')],
  },
]

export default moviedata;