 
var moviedata=[
  {
    id: 1,
    nameChinese:'绿皮书',
    nameEnglish:'Green Book',
    prop:'剧情 喜剧 传记',
    country:'美国/130分钟',
    score: '豆瓣：8.9',
    language:'我住在城堡里，孤身一人',
    home: require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/1.jpg'),name:'彼得·法雷里', name2:'导演'},
            {arl:require('./image/week1/2.jpg'),name:'维果·莫腾森', name2:'饰 托尼·利'},
            {arl:require('./image/week1/3.jpg'),name:'马赫沙拉·阿里', name2:'饰 唐·雪利'},
            {arl:require('./image/week1/4.jpg'),name:'琳达·卡德里尼', name2:'饰 德洛瑞丝'},
            {arl:require('./image/week1/5.jpg'),name:'塞巴斯·马尼斯科', name2:'饰 约翰尼'},
            {arl:require('./image/week1/6.jpg'),name:'迪米特·马里诺夫', name2:'饰 奥列格'},
            {arl:require('./image/week1/7.jpg'),name:'迈克·哈顿', name2:'饰 乔治'},
          ],
     vedio:[
            {arl:require('./image/week1/11.jpg') },
            {arl:require('./image/week1/12.jpg') },
            {arl:require('./image/week1/13.jpg') },
            {arl:require('./image/week1/14.jpg') },
            {arl:require('./image/week1/15.jpg') },
            {arl:require('./image/week1/16.jpg') },
            {arl:require('./image/week1/17.jpg') },
            {arl:require('./image/week1/18.jpg') },
         ],
      expand:'https://movie.douban.com/subject/27060077/',
      lan:[
         
        {intro:'The world is full of lonely people waiting to make the first move.',
        intro2:' 世界上孤独的人都害怕迈出第一步。',
        intro3:'--绿皮书   '}, 
        {intro:'You never win with violence. You only win when you maintain your dignity.',
        intro2:'你永远不会以暴力取胜。只有保持尊严才能战胜一切。',
        intro3:'--绿皮书   '}, 
        {intro:'I am not white enough, not black enough and even not man enough.',
        intro2:' 我不够白，也不够黑，甚至不够男人。',
        intro3:'--绿皮书   '}, 
        {intro:'The world is full of lonely people waiting to make the first move.',
        intro2:' 世界上孤独的人都害怕迈出第一步',
        intro3:'--绿皮书   '}, 
        {intro:'The world is full of lonely people waiting to make the first move.',
        intro2:' 世界上孤独的人都害怕迈出第一步',
        intro3:'--绿皮书   '}, 
      ]
  },
  {
    id: 2,
    nameChinese:'海蒂和爷爷',
    nameEnglish:'Heidi ',
    prop:'剧情 家庭 冒险',
    country:'德国/111分钟',
    score: '豆瓣：9.1',
    language:'如果生活中有什么使你感到快乐，那就去做吧，不要管别人说了什么',
    home:require('./image/week2/home.jpg'),
    detail:require('./image/week2/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week2/1.jpg'),name:'阿兰·葛斯彭纳', name2:'导演'},
            {arl:require('./image/week2/2.jpg'),name:'阿努克·斯特芬', name2:'饰 海蒂'},
            {arl:require('./image/week2/3.jpg'),name:'布鲁诺·甘茨', name2:'饰 爷爷'},
            {arl:require('./image/week2/4.jpg'),name:'昆林·艾格匹', name2:'饰 彼得 '},
            {arl:require('./image/week2/5.jpg'),name:'安娜·申茨', name2:'饰 姨妈'},
            {arl:require('./image/week2/6.jpg'),name:'伊莎贝尔·奥特曼', name2:'饰 克拉拉'},
            {arl:require('./image/week2/7.jpg'),name:'莉莲·奈福', name2:'饰 巴贝儿'},
          ],
     vedio:[
            {arl:require('./image/week2/11.jpg') },
            {arl:require('./image/week2/12.jpg') },
            {arl:require('./image/week2/13.jpg') },
            {arl:require('./image/week2/14.jpg') },
            {arl:require('./image/week2/15.jpg') },
            {arl:require('./image/week2/16.jpg') },
            {arl:require('./image/week2/17.jpg') },
            {arl:require('./image/week2/18.jpg') },
            {arl:require('./image/week2/19.jpg') },
            {arl:require('./image/week2/20.jpg') },
            {arl:require('./image/week2/21.jpg') }, 
 ],
 expand:'https://movie.douban.com/subject/25958717/',
  },
  {
    id: 3,
    nameChinese:'奇迹男孩',
    nameEnglish:'Wonder',
    prop:'剧情 家庭 儿童',
    country:'美国/113分钟',
    score: "豆瓣: 8.6",
    language:'你就是一个奇迹男孩',
    home:require('./image/week3/home.jpg'),
    detail:require('./image/week3/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week3/1.jpg'),name:'斯蒂芬·卓博斯基', name2:'导演'},
            {arl:require('./image/week3/2.jpg'),name:'雅各布·特伦布莱', name2:'饰 奥吉'},
            {arl:require('./image/week3/3.jpg'),name:'朱莉娅·罗伯茨', name2:'饰 伊莎贝尔'},
            {arl:require('./image/week3/4.jpg'),name:'伊扎贝拉·维多维', name2:'饰 维娅'},
            {arl:require('./image/week3/5.jpg'),name:'欧文·威尔逊', name2:'饰 内特'},
            {arl:require('./image/week3/6.jpg'),name:'诺亚·尤佩', name2:'饰 杰克·威尔'},
            {arl:require('./image/week3/7.jpg'),name:'丹妮尔·罗丝', name2:'饰 米兰达'},
          ],
     vedio:[
            {arl:require('./image/week3/11.jpg') },
            {arl:require('./image/week3/12.jpg') },
            {arl:require('./image/week3/13.jpg') },
            {arl:require('./image/week3/14.jpg') },
            {arl:require('./image/week3/15.jpg') },
            {arl:require('./image/week3/16.jpg') },
            {arl:require('./image/week3/17.jpg') },
            {arl:require('./image/week3/18.jpg') },
            {arl:require('./image/week3/19.jpg') },
            {arl:require('./image/week3/20.jpg') },
            {arl:require('./image/week3/21.jpg') },
            {arl:require('./image/week3/22.jpg') },
    ],
    expand:'https://movie.douban.com/subject/26787574/',
  },
  {
    id: 4,
    nameChinese:'天才少女 ',
    nameEnglish:'Gifted',
    prop:'剧情 家庭',
    country:'美国/101分钟',
    score: '豆瓣：8.2',
    language:' ',
    home:require('./image/week4/home.jpg'),
    detail:require('./image/week4/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week4/home.jpg'),name:'马克·韦布', name2:'导演'},
            {arl:require('./image/week4/home.jpg'),name:'克里斯·埃文斯', name2:'饰 弗兰克·阿德勒'},
            {arl:require('./image/week4/home.jpg'),name:'珍妮·斯蕾特', name2:'饰 邦妮·史蒂文森'},
            {arl:require('./image/week4/home.jpg'),name:'琳赛·邓肯', name2:'饰 伊芙琳·阿德勒'},
            {arl:require('./image/week4/home.jpg'),name:'麦肯娜·格瑞丝', name2:'饰 玛丽·阿德勒'},
            {arl:require('./image/week4/home.jpg'),name:'奥克塔维亚', name2:'饰 罗伯塔·泰勒 '},
            {arl:require('./image/week4/home.jpg'),name:'维迈克尔·肯德尔', name2:'饰 贾斯汀·吉尔莫尔 '},
          ],
     vedio:[
            {arl:require('./image/week4/11.jpg') },
            {arl:require('./image/week4/12.jpg') },
            {arl:require('./image/week4/13.jpg') },
            {arl:require('./image/week4/14.jpg') },
            {arl:require('./image/week4/15.jpg') },
            {arl:require('./image/week4/16.jpg') },
            {arl:require('./image/week4/17.jpg') },
            {arl:require('./image/week4/18.jpg') },
            {arl:require('./image/week4/19.jpg') },
            {arl:require('./image/week4/20.jpg') },
 ],
  expand:'https://movie.douban.com/subject/26593587/',
  },
  {
    id: 5,
    nameChinese:'摔跤吧！爸爸',
    nameEnglish:'Dangal',
    prop:'剧情 家庭 传记 运动',
    country:'印度/140分钟',
    score: 5,
    language:' ',
    home:require('./image/week5/home.jpg'),
    detail:require('./image/week5/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week5/home.jpg'),name:'涅提·蒂瓦里', name2:'导演'},
            {arl:require('./image/week5/home.jpg'),name:'阿米尔·汗', name2:'饰 马哈维亚·辛格'},
            {arl:require('./image/week5/home.jpg'),name:'法缇玛·萨那', name2:'饰 吉塔·珀尕'},
            {arl:require('./image/week5/home.jpg'),name:'桑亚·玛荷塔', name2:'饰 芭比塔·库马尔·'},
            {arl:require('./image/week5/home.jpg'),name:'阿帕尔夏克提', name2:'饰 奥姆卡尔'},
            {arl:require('./image/week5/home.jpg'),name:'沙克希·坦沃', name2:'饰 达雅·考尔'},
            {arl:require('./image/week5/home.jpg'),name:'塞伊拉·沃西', name2:'饰 小吉塔'},
          ],
     vedio:[
            {arl:require('./image/week5/11.jpg') },
            {arl:require('./image/week5/12.jpg') },
            {arl:require('./image/week5/13.jpg') },
            {arl:require('./image/week5/14.jpg') },
            {arl:require('./image/week5/15.jpg') },
            {arl:require('./image/week5/16.jpg') },
            {arl:require('./image/week5/17.jpg') },
            {arl:require('./image/week5/18.jpg') },
            {arl:require('./image/week5/19.jpg') },
            {arl:require('./image/week5/20.jpg') },
      ],
    expand:'https://movie.douban.com/subject/26387939/',
  },
  {
    id: 6,
    nameChinese:'我不是药神',
    nameEnglish:'Save',
    prop:'剧情 喜剧',
    country:'中国/117分钟',
    score: '豆瓣：9.0',
    language:' ',
    home:require('./image/week6/home.jpg'),
    detail:require('./image/week6/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week6/home.jpg'),name:'文牧野', name2:'导演'},
            {arl:require('./image/week6/home.jpg'),name:'陈峥', name2:'饰 程勇'},
            {arl:require('./image/week6/home.jpg'),name:'王传君', name2:'饰 吕受益'},
            {arl:require('./image/week6/home.jpg'),name:'周一围', name2:'饰 曹斌'},
            {arl:require('./image/week6/home.jpg'),name:'谭卓', name2:'饰 刘思慧'},
            {arl:require('./image/week6/home.jpg'),name:'章宇', name2:'饰 黄毛'},
            {arl:require('./image/week6/home.jpg'),name:'杨新鸣', name2:'饰 刘牧师'},
          ],
     vedio:[
            {arl:require('./image/week6/11.jpg') },
            {arl:require('./image/week6/12.jpg') },
            {arl:require('./image/week6/13.jpg') },
            {arl:require('./image/week6/14.jpg') },
            {arl:require('./image/week6/15.jpg') },
            {arl:require('./image/week6/16.jpg') },
            {arl:require('./image/week6/17.jpg') },
            {arl:require('./image/week6/18.jpg') },
            {arl:require('./image/week6/19.jpg') },
            {arl:require('./image/week6/20.jpg') },
            {arl:require('./image/week6/21.jpg') },
     ],
     expand:'https://movie.douban.com/subject/26752088/',
  },
  {
    id: 7,
    nameChinese:'头号玩家',
    nameEnglish:'Ready Player One',
    prop:'动作 科幻 冒险',
    country:'美国/140分钟',
    score: '豆瓣：8.7',
    language:'谢谢你玩我的游戏',
    home:require('./image/week7/home.jpg'),
    detail:require('./image/week7/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ 
            {arl:require('./image/week7/home.jpg'),name:'史蒂文·斯皮尔伯格 ', name2:'导演'},
            {arl:require('./image/week7/home.jpg'),name:'泰伊·谢里丹', name2:'饰 韦德·沃兹'},
            {arl:require('./image/week7/home.jpg'),name:'奥利维亚·库克', name2:'饰 萨曼莎'},
            {arl:require('./image/week7/home.jpg'),name:'本·门德尔森 ', name2:'饰 诺兰·索伦托'},
            {arl:require('./image/week7/home.jpg'),name:'马克·里朗斯', name2:'饰 詹姆斯·哈利迪'},
            {arl:require('./image/week7/home.jpg'),name:'丽娜·维特', name2:'饰 艾奇'},
            {arl:require('./image/week7/home.jpg'),name:'森崎温', name2:'饰 大东'},
          ],
    vedio: [
            {arl:require('./image/week7/11.jpg') },
            {arl:require('./image/week7/12.jpg') },
            {arl:require('./image/week7/13.jpg') },
            {arl:require('./image/week7/14.jpg') },
            {arl:require('./image/week7/15.jpg') },
            {arl:require('./image/week7/16.jpg') },
            {arl:require('./image/week7/17.jpg') },
            {arl:require('./image/week7/18.jpg') },
     ],
    expand:'https://movie.douban.com/subject/4920389/',
  },
]

export default moviedata;